Uber Eats by Vladyslav Sak
VladyslavSak/layout_ubereats pull request #1
Opened 2019-08-06 20:13 UTC by VladyslavSak

2019-08-08 07:34 UTC, danheim commented
Добавь ссылку на просмотр в описание пул реквеста.

Отсутствует адресс доставки в мобильной версии.
<img width="502" alt="Screen Shot 2019-08-08 at 10 28 31 AM" src="https://user-images.githubusercontent.com/36257947/62683582-768b9380-b9c7-11e9-8d51-82ba53c4a8ad.png">

Адрес и время доставки ломаются при среднем разрешении
<img width="738" alt="Screen Shot 2019-08-08 at 10 31 48 AM" src="https://user-images.githubusercontent.com/36257947/62683718-c8ccb480-b9c7-11e9-8809-4ae20e9b1fd5.png">


Инпут внутри не отцентрован. Размер шрифта ввода == размер шрифта плейсхолдера
<img width="452" alt="Screen Shot 2019-08-08 at 10 30 01 AM" src="https://user-images.githubusercontent.com/36257947/62683605-886d3680-b9c7-11e9-852e-91172ccc162c.png">

Кнопки должны быть разные
<img width="210" alt="Screen Shot 2019-08-08 at 10 30 34 AM" src="https://user-images.githubusercontent.com/36257947/62683627-9327cb80-b9c7-11e9-8969-34c4acb851a1.png">

Плейсхолдер должен быть серым, размер шрифта инпута должен соответствовать размеру шрифта плейсхолдера
<img width="423" alt="Screen Shot 2019-08-08 at 10 30 58 AM" src="https://user-images.githubusercontent.com/36257947/62683650-a20e7e00-b9c7-11e9-9ee7-b96dac51b8c3.png">

Выбор языка
<img width="320" alt="Screen Shot 2019-08-08 at 10 32 45 AM" src="https://user-images.githubusercontent.com/36257947/62683754-e568ec80-b9c7-11e9-8554-2d53910a8697.png">

Отсутствуют иконки соц сетей

2019-08-08 07:42 UTC, danheim requested changes

2019-08-08 07:42 UTC, danheim commented on src/index.html
> +
пустая строка

2019-08-08 07:42 UTC, danheim commented on src/index.html
> +
пустая строка

2019-08-08 07:42 UTC, danheim commented on src/index.html
> +
пустая строка не нужна

2019-08-08 07:42 UTC, danheim commented on src/index.html
> +          <a href="#" class="apps__link">
отступы поправь

2019-08-08 07:46 UTC, danheim requested changes

2019-08-08 07:46 UTC, danheim commented on src/styles/_media-query.scss
> +    padding-right: 8px;
`padding: 0 8px;`

2019-08-08 13:55 UTC, VladyslavSak commented on src/styles/_media-query.scss
> +    padding-right: 8px;
I need to change only horizontal padding.

2019-08-08 13:55 UTC, VladyslavSak commented
> Отсутствуют иконки соц сетей.
> Добавь плавную прокрутку при нажатии на стрелочку внизу (scroll-behavior)

![image](https://user-images.githubusercontent.com/50458410/62707575-46a9b380-b9fa-11e9-8e7d-ebc6a3d24386.png)
 I have these select and social icons.

2019-08-08 13:58 UTC, VladyslavSak commented
Link on demo:
https://vladyslavsak.github.io/layout_ubereats/

2019-08-09 07:52 UTC, danheim commented
Ввода текста с левого края, не по центру
<img width="420" alt="Screen Shot 2019-08-09 at 10 49 43 AM" src="https://user-images.githubusercontent.com/36257947/62763112-73f67000-ba93-11e9-90a6-0d26c07007a6.png">

Давай отцентруем иконку и сделаем ей отступы от левого края
<img width="317" alt="Screen Shot 2019-08-09 at 10 50 21 AM" src="https://user-images.githubusercontent.com/36257947/62763147-883a6d00-ba93-11e9-8245-e99d6681a44b.png">

Не исправлено
<img width="273" alt="Screen Shot 2019-08-09 at 10 50 59 AM" src="https://user-images.githubusercontent.com/36257947/62763176-9a1c1000-ba93-11e9-8515-7148e361d0b9.png">

Блок адреса и времени должен занимать одинаковую ширину с другими контейнерами
<img width="668" alt="Screen Shot 2019-08-09 at 10 51 28 AM" src="https://user-images.githubusercontent.com/36257947/62763206-b029d080-ba93-11e9-807f-160050d8d8fa.png">
(Тоже самое в мобильной версии, где всего 1 карточка в ряду)

2019-08-09 08:04 UTC, danheim requested changes
Убери ненужные пустые строки
<img width="688" alt="Screen Shot 2019-08-09 at 11 03 25 AM" src="https://user-images.githubusercontent.com/36257947/62763947-6510bd00-ba95-11e9-95ba-b50e3de0b38e.png">

<img width="662" alt="Screen Shot 2019-08-09 at 10 52 54 AM" src="https://user-images.githubusercontent.com/36257947/62763946-64782680-ba95-11e9-8edf-688e4c40b278.png">

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +        <label for="time" class="name time">
что значит `name time`?

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +          <span class="footer__body__hashtag"><span>#</span>UberEats</span>
если это бем, то не может быть больше одного `двойного нижнего подчеркивания`

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +          <div class="footer__website website">
думаю тут подойдет название `social`

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +        <a href="#" class="footer__menu__item">
```suggestion
        <a href="#" class="footer__menu-item">
```

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +          <img src="./images/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.png" alt="AppleStore Download" class="apps__img">
давай будем переносить очень длинные теги
```suggestion
          <img
            src="./images/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.png"
            alt="AppleStore Download" class="apps__img"
          >
```

2019-08-09 08:04 UTC, danheim commented on src/index.html
> +        <p class="footer__bottom--copyright">©    2019 Uber Technologies Inc.
```suggestion
        <p class="footer__bottom--copyright">
          © 2019 Uber Technologies Inc.
```

2019-08-12 07:16 UTC, VladyslavSak commented on src/index.html
> +          <div class="footer__website website">
If I change a word on social, the test will not work, because the test doesn't agree with this word.

2019-08-12 07:23 UTC, VladyslavSak commented
![normalize select](https://user-images.githubusercontent.com/50458410/62850326-37bd4c80-bceb-11e9-8a29-54d42bf415a5.png)
I have a normal view of this select.

2019-08-13 08:47 UTC, danheim commented on src/index.html
> +          <div class="footer__website website">
не может такого быть

2019-08-13 08:51 UTC, danheim requested changes
Наведи, пожалуйста, порядок в классах
http://getbem.com/naming/

2019-08-13 08:51 UTC, danheim commented on src/index.html
> +      <div class="order__info">
BEM: `block__element`, если это order и info элемент, то где сам блок order?

2019-08-14 12:25 UTC, VladyslavSak commented
https://vladyslavsak.github.io/layout_ubereats/ - ще раз посилання, щоб не шукати

2019-08-14 13:10 UTC, danheim approved these changes

2019-08-16 16:27 UTC, merged